name: CI - Payment Service React

on:
  push:
    branches:
      - master
      - devops-setup
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # ✅ Ignorer l'absence de tests
      - name: Run tests (ignore if no tests)
        run: npm test -- --passWithNoTests

      - name: Build React App
        run: CI=false npm run build
