name: CI - Payment Service React

on:
  push:
    branches:
      - master
      - devops-setup
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Lancer les tests (si tu as des tests unitaires)
      - name: Run tests
        run: npm test --if-present

      # 5. Build de l'application React
      - name: Build React App
        run: npm run build
